PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX mdmp: <https://ontology.openidentityexchange.org/riskmodel#>
PREFIX oix: <https://www.openidentityexchange.org/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?hasBiometricInformationCheckedBy from <g1> WHERE {

?hasBiometricInformationCheckedBy <http://www.w3.org/2000/01/rdf-schema#label> 'hasBiometricInformationCheckedBy' .

} 

